# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyANSRSource', '0104_auto_20161021_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectClassificationMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defectclassificationmaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defectclassificationmaster_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefectSeverityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defectseveritylevel_created_by', to=settings.AUTH_USER_MODEL)),
                ('defect_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.DefectClassificationMaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefectTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defecttypemaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defecttypemaster_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectChapterReviewerRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_chapter_reviewer_relationship_author', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Chapter', verbose_name='Chapter/Subtitle')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectchapterreviewerrelationship_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecttemplate_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('review_item', models.CharField(max_length=100)),
                ('defect', models.TextField()),
                ('is_fixed', models.BooleanField(default=True, verbose_name='Is Fixed?')),
                ('remarks', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewerreport_created_by', to=settings.AUTH_USER_MODEL)),
                ('defect_severity_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.DefectSeverityLevel')),
                ('fixed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_report_fixed_by', to=settings.AUTH_USER_MODEL)),
                ('project_chapter_reviewer_relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ProjectChapterReviewerRelationship')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewerreport_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeverityLevelMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='severitylevelmaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='severitylevelmaster_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templatemaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templatemaster_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reviewergroup',
            name='review_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ReviewerMaster'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.TemplateMaster'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecttemplate_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectchapterreviewerrelationship',
            name='review_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ReviewerGroup'),
        ),
        migrations.AddField(
            model_name='projectchapterreviewerrelationship',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_chapter_reviewer_relationship_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectchapterreviewerrelationship',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectchapterreviewerrelationship_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defectseveritylevel',
            name='reviewer_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ReviewerGroup'),
        ),
        migrations.AddField(
            model_name='defectseveritylevel',
            name='severity_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.SeverityLevelMaster'),
        ),
        migrations.AddField(
            model_name='defectseveritylevel',
            name='severity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.DefectTypeMaster'),
        ),
        migrations.AddField(
            model_name='defectseveritylevel',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.TemplateMaster'),
        ),
        migrations.AddField(
            model_name='defectseveritylevel',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defectseveritylevel_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
