# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-19 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyANSRSource', '0114_auto_20170601_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Chapter', verbose_name='Chapter/Subtitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componentmaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componentmaster_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefectClassificationMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defectclassificationmaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defectclassificationmaster_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefectSeverityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product_type', models.CharField(blank=True, choices=[(0, 'assessment'), ('1', 'learning')], default=0, max_length=50, null=True, verbose_name='Product')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defectseveritylevel_created_by', to=settings.AUTH_USER_MODEL)),
                ('defect_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.DefectClassificationMaster')),
            ],
        ),
        migrations.CreateModel(
            name='DefectTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defecttypemaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defecttypemaster_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DSLTemplateReviewGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsltemplatereviewgroup_created_by', to=settings.AUTH_USER_MODEL)),
                ('defect_severity_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.DefectSeverityLevel')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalQASheetHeader',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('count', models.IntegerField(default=0, verbose_name='work packet count')),
                ('review_group_feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('review_group_status', models.BooleanField(default=False, verbose_name=' Is Review Completed ')),
                ('author_feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('author_feedback_status', models.BooleanField(default=False, verbose_name=' Is author feedback Completed ')),
                ('order_number', models.IntegerField(verbose_name='Review tab Order')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MyANSRSource.Chapter')),
                ('chapter_component', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='QMS.ChapterComponent')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MyANSRSource.Project')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical qa sheet header',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReviewReport',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('review_item', models.CharField(max_length=100)),
                ('defect', models.TextField()),
                ('instruction', models.TextField(blank=True, null=True, verbose_name='Instruction to fix')),
                ('screen_shot', models.TextField(blank=True, max_length=100, null=True, verbose_name='upload screen shot')),
                ('is_fixed', models.CharField(blank=True, choices=[('', '------'), ('Fixed', 'Fixed'), ('FixNotRequired', 'Fix Not Required')], max_length=50, null=True, verbose_name='Is Fixed?')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical review report',
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplateProcessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lead_review_status', models.BooleanField(default=False, verbose_name=' Is Lead Review Completed ')),
                ('lead_review_feedback', models.TextField(blank=True, null=True, verbose_name=' Lead Review Feedback ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projecttemplateprocessmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project')),
            ],
            options={
                'ordering': ['lead_review_status'],
            },
        ),
        migrations.CreateModel(
            name='QASheetHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0, verbose_name='work packet count')),
                ('review_group_feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('review_group_status', models.BooleanField(default=False, verbose_name=' Is Review Completed ')),
                ('author_feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('author_feedback_status', models.BooleanField(default=False, verbose_name=' Is author feedback Completed ')),
                ('order_number', models.IntegerField(verbose_name='Review tab Order')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QASheetHeader_author', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Chapter', verbose_name='Chapter/Subtitle')),
                ('chapter_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS.ChapterComponent', verbose_name='Chapter&Component')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qasheetheader_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QMSProcessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('product_type', models.CharField(blank=True, choices=[(0, 'assessment'), ('1', 'learning')], default=0, max_length=50, null=True, verbose_name='Product')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qmsprocessmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qmsprocessmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='alias/display name for review group')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('review_item', models.CharField(max_length=100)),
                ('defect', models.TextField()),
                ('instruction', models.TextField(blank=True, null=True, verbose_name='Instruction to fix')),
                ('screen_shot', models.FileField(blank=True, null=True, upload_to='qms', verbose_name='upload screen shot')),
                ('is_fixed', models.CharField(blank=True, choices=[('', '------'), ('Fixed', 'Fixed'), ('FixNotRequired', 'Fix Not Required')], max_length=50, null=True, verbose_name='Is Fixed?')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('QA_sheet_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.QASheetHeader')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewreport_created_by', to=settings.AUTH_USER_MODEL)),
                ('defect_severity_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.DefectSeverityLevel')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_report_fixed_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewreport_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeverityLevelMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('penalty_count', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Penalty Count')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='severitylevelmaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='severitylevelmaster_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('actual_name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templatemaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templatemaster_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateProcessReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Is Mandatory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templateprocessreview_created_by', to=settings.AUTH_USER_MODEL)),
                ('qms_process_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.QMSProcessModel')),
                ('review_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ReviewGroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.TemplateMaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templateprocessreview_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkPacketMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workpacketmaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workpacketmaster_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reviewgroup',
            name='review_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ReviewMaster'),
        ),
        migrations.AddField(
            model_name='qasheetheader',
            name='review_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ReviewGroup'),
        ),
        migrations.AddField(
            model_name='qasheetheader',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QASheetHeader_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qasheetheader',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qasheetheader_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qasheetheader',
            name='work_packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS.WorkPacketMaster', verbose_name='work packet (output)'),
        ),
        migrations.AddField(
            model_name='projecttemplateprocessmodel',
            name='qms_process_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.QMSProcessModel'),
        ),
        migrations.AddField(
            model_name='projecttemplateprocessmodel',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.TemplateMaster'),
        ),
        migrations.AddField(
            model_name='projecttemplateprocessmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projecttemplateprocessmodel_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreviewreport',
            name='QA_sheet_header',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='QMS.QASheetHeader'),
        ),
        migrations.AddField(
            model_name='historicalreviewreport',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreviewreport',
            name='defect_severity_level',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='QMS.DefectSeverityLevel'),
        ),
        migrations.AddField(
            model_name='historicalreviewreport',
            name='fixed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreviewreport',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreviewreport',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalqasheetheader',
            name='review_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='QMS.ReviewGroup'),
        ),
        migrations.AddField(
            model_name='historicalqasheetheader',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalqasheetheader',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalqasheetheader',
            name='work_packet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='QMS.WorkPacketMaster'),
        ),
        migrations.AddField(
            model_name='dsltemplatereviewgroup',
            name='review_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ReviewMaster'),
        ),
        migrations.AddField(
            model_name='dsltemplatereviewgroup',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.TemplateMaster'),
        ),
        migrations.AddField(
            model_name='dsltemplatereviewgroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsltemplatereviewgroup_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defectseveritylevel',
            name='severity_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.SeverityLevelMaster'),
        ),
        migrations.AddField(
            model_name='defectseveritylevel',
            name='severity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.DefectTypeMaster'),
        ),
        migrations.AddField(
            model_name='defectseveritylevel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defectseveritylevel_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chaptercomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ComponentMaster', verbose_name='Component'),
        ),
        migrations.AddField(
            model_name='chaptercomponent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaptercomponent_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chaptercomponent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaptercomponent_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dsltemplatereviewgroup',
            unique_together=set([('defect_severity_level', 'template')]),
        ),
        migrations.AlterUniqueTogether(
            name='defectseveritylevel',
            unique_together=set([('severity_type', 'severity_level', 'defect_classification')]),
        ),
    ]
