# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchapterreviewerrelationship',
            name='questions',
            field=models.IntegerField(default=0),
        ),
    ]
