# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyANSRSource', '0104_auto_20161021_1111'),
        ('QMS', '0002_projectchapterreviewerrelationship_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QASheetHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0, verbose_name='work packet count')),
                ('review_group_status', models.BooleanField(default=False, verbose_name=' Is Review Completed ')),
                ('author_feedback_status', models.BooleanField(default=False, verbose_name=' Is author feedback Completed ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QASheetHeader_author', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Chapter', verbose_name='Chapter/Subtitle')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qasheetheader_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('review_item', models.CharField(max_length=100)),
                ('defect', models.TextField()),
                ('is_fixed', models.BooleanField(default=True, verbose_name='Is Fixed?')),
                ('remarks', models.TextField()),
                ('QA_sheet_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.QASheetHeader')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewreport_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkPacketMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpacketmaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpacketmaster_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='ReviewerGroup',
            new_name='ReviewGroup',
        ),
        migrations.RenameModel(
            old_name='ReviewerMaster',
            new_name='ReviewMaster',
        ),
        migrations.RemoveField(
            model_name='projectchapterreviewerrelationship',
            name='author',
        ),
        migrations.RemoveField(
            model_name='projectchapterreviewerrelationship',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='projectchapterreviewerrelationship',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectchapterreviewerrelationship',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectchapterreviewerrelationship',
            name='review_group',
        ),
        migrations.RemoveField(
            model_name='projectchapterreviewerrelationship',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='projectchapterreviewerrelationship',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='reviewerreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reviewerreport',
            name='defect_severity_level',
        ),
        migrations.RemoveField(
            model_name='reviewerreport',
            name='fixed_by',
        ),
        migrations.RemoveField(
            model_name='reviewerreport',
            name='project_chapter_reviewer_relationship',
        ),
        migrations.RemoveField(
            model_name='reviewerreport',
            name='updated_by',
        ),
        migrations.RenameField(
            model_name='defectseveritylevel',
            old_name='reviewer_group',
            new_name='review_group',
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='lead_review_status',
            field=models.BooleanField(default=False, verbose_name=' Is Lead Review Completed '),
        ),
        migrations.DeleteModel(
            name='ProjectChapterReviewerRelationship',
        ),
        migrations.DeleteModel(
            name='ReviewerReport',
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='defect_severity_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.DefectSeverityLevel'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='fixed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_report_fixed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewreport_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qasheetheader',
            name='review_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ReviewGroup'),
        ),
        migrations.AddField(
            model_name='qasheetheader',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QASheetHeader_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qasheetheader',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qasheetheader_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qasheetheader',
            name='work_packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.WorkPacketMaster', verbose_name='work packet (output)'),
        ),
    ]
