# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0003_auto_20161102_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreport',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_report_fixed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='Is Fixed?'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
