# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0005_reviewreport_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qasheetheader',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QASheetHeader_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
