# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QMS', '0006_auto_20161103_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='QMSProcessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qmsprocessmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qmsprocessmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateProcessReviewerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Is Mandatory?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templateprocessreviewergroup_created_by', to=settings.AUTH_USER_MODEL)),
                ('qms_process_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.QMSProcessModel')),
                ('review_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ReviewGroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.TemplateMaster')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templateprocessreviewergroup_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
