# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0007_qmsprocessmodel_templateprocessreviewergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateprocessreviewergroup',
            name='qms_process_model',
        ),
        migrations.AddField(
            model_name='templateprocessreviewergroup',
            name='qms_process_model',
            field=models.ManyToManyField(to='QMS.QMSProcessModel'),
        ),
        migrations.RemoveField(
            model_name='templateprocessreviewergroup',
            name='review_group',
        ),
        migrations.AddField(
            model_name='templateprocessreviewergroup',
            name='review_group',
            field=models.ManyToManyField(to='QMS.ReviewGroup'),
        ),
    ]
