# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QMS', '0008_auto_20161111_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateProcessReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Is Mandatory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templateprocessreview_created_by', to=settings.AUTH_USER_MODEL)),
                ('qms_process_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.QMSProcessModel')),
                ('review_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ReviewGroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.TemplateMaster')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templateprocessreview_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='qms_process_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QMS.QMSProcessModel'),
            preserve_default=False,
        ),
    ]
