# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyANSRSource', '0104_auto_20161021_1111'),
        ('QMS', '0009_auto_20161114_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplateProcessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lead_review_status', models.BooleanField(default=False, verbose_name=' Is Lead Review Completed ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecttemplateprocessmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project')),
                ('qms_process_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.QMSProcessModel')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.TemplateMaster')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecttemplateprocessmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='qms_process_model',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='template',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='templateprocessreviewergroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='templateprocessreviewergroup',
            name='qms_process_model',
        ),
        migrations.RemoveField(
            model_name='templateprocessreviewergroup',
            name='review_group',
        ),
        migrations.RemoveField(
            model_name='templateprocessreviewergroup',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templateprocessreviewergroup',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ProjectTemplate',
        ),
        migrations.DeleteModel(
            name='TemplateProcessReviewerGroup',
        ),
    ]
