# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 05:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyANSRSource', '0104_auto_20161021_1111'),
        ('QMS', '0011_historicalqasheetheader_historicalreviewreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Chapter', verbose_name='Chapter/Subtitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentmaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentmaster_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='historicalreviewreport',
            name='is_fixed',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('fix_not_required', 'Fix Not Required')], max_length=50, null=True, verbose_name='Is Fixed?'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='is_fixed',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('fix_not_required', 'Fix Not Required')], max_length=50, null=True, verbose_name='Is Fixed?'),
        ),
        migrations.AddField(
            model_name='chaptercomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QMS.ComponentMaster', verbose_name='Component'),
        ),
        migrations.AddField(
            model_name='chaptercomponent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaptercomponent_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chaptercomponent',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaptercomponent_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalqasheetheader',
            name='chapter_component',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='QMS.ChapterComponent'),
        ),
        migrations.AddField(
            model_name='qasheetheader',
            name='chapter_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS.ChapterComponent', verbose_name='Chapter&Component'),
        ),
    ]
