# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0013_auto_20161121_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qasheetheader',
            name='work_packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS.WorkPacketMaster', verbose_name='work packet (output)'),
        ),
    ]
