# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0014_auto_20161121_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='severitylevelmaster',
            name='penalty_count',
            field=models.IntegerField(default=0, verbose_name='Penalty Count'),
            preserve_default=False,
        ),
    ]
