# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0015_severitylevelmaster_penalty_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severitylevelmaster',
            name='penalty_count',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Penalty Count'),
        ),
    ]
