# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0016_auto_20161125_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentmaster',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='defectclassificationmaster',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='defecttypemaster',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='qmsprocessmodel',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='reviewmaster',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='severitylevelmaster',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='templatemaster',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='workpacketmaster',
            old_name='active',
            new_name='is_active',
        ),
    ]
