# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0017_auto_20161128_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectseveritylevel',
            name='review_group',
        ),
        migrations.AddField(
            model_name='defectseveritylevel',
            name='review_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QMS.ReviewMaster'),
            preserve_default=False,
        ),
    ]
