# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0018_auto_20161201_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalqasheetheader',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Review tab Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qasheetheader',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Review tab Order'),
            preserve_default=False,
        ),
    ]
