# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0020_auto_20161206_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreviewreport',
            name='screen_shot',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='screen_shot',
            field=models.ImageField(blank=True, null=True, upload_to='qms'),
        ),
    ]
