# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0021_auto_20161208_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreport',
            name='screen_shot',
            field=models.FileField(blank=True, null=True, upload_to='qms'),
        ),
    ]
