# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, verbose_name='Skill Name')),
                ('level1', models.TextField(max_length=500, verbose_name='Level1')),
                ('level2', models.TextField(max_length=500, verbose_name='Level2')),
                ('level3', models.TextField(max_length=500, verbose_name='Level3')),
            ],
            options={
                'verbose_name': 'Skill List',
            },
        ),
        migrations.CreateModel(
            name='User_Skills',
            fields=[
                ('sid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('emp_mid', models.CharField(default='', max_length=20, verbose_name='Employee ID')),
                ('skills_name', models.CharField(default='', max_length=300, verbose_name='Skill Name')),
                ('skills_type', models.CharField(default='', max_length=10, verbose_name='Skill Level')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='created Date')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'User Skills',
            },
        ),
    ]
