# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-20 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0027_auto_20170302_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, verbose_name='Skill Name')),
                ('level1', models.TextField(max_length=500, verbose_name='Level1')),
                ('level2', models.TextField(max_length=500, verbose_name='Level2')),
                ('level3', models.TextField(max_length=500, verbose_name='Level3')),
            ],
            options={
                'verbose_name': 'Skill List',
            },
        ),
        migrations.CreateModel(
            name='User_Skills',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('skills_type', models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], default='', max_length=10, verbose_name='Skill Level')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='created Date')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Updated Date')),
                ('emp_mid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee ID')),
                ('skills_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='skills_name', to='skillset.Skill_Lists', verbose_name='Skill Name')),
            ],
            options={
                'verbose_name': 'User Skills',
            },
        ),
    ]
