# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_skills',
            name='skill_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_level', to='skillset.Skill_Lists', verbose_name='Skill Level'),
        ),
    ]
