# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillset', '0002_auto_20170304_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_skills',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='user_skills',
            name='skill_level',
            field=models.ManyToManyField(related_name='skills_level', to='skillset.Skill_Lists', verbose_name='Skill Level'),
        ),
    ]
