# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillset', '0003_auto_20170304_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_skills',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='user_skills',
            name='skill_level',
            field=models.CharField(choices=[('L1', 'LEVEL 1'), ('L2', 'LEVEL 2'), ('L3', 'LEVEL 3')], default=1, max_length=10, verbose_name='Skill Level'),
            preserve_default=False,
        ),
    ]
