# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillset', '0004_auto_20170304_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_skills',
            name='skill_id',
        ),
        migrations.RemoveField(
            model_name='user_skills',
            name='skill_name',
        ),
        migrations.AddField(
            model_name='user_skills',
            name='skill_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills_name', to='skillset.Skill_Lists', verbose_name='Skill Name'),
            preserve_default=False,
        ),
    ]
