# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 09:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grievances', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grievances_catagory',
            new_name='Grievances_category',
        ),
        migrations.RenameField(
            model_name='grievances',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='grievances_category',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='grievances',
            name='grievance_status',
            field=models.CharField(choices=[(b'new', b'New'), (b'opened', b'Open'), (b'in_progress', b'In Progress'), (b'closed', b'Closed')], default=b'new', max_length=50),
        ),
        migrations.AlterField(
            model_name='grievances',
            name='action_taken',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='grievances',
            name='admin_closure_message',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='grievances',
            name='grievance',
            field=models.TextField(help_text=b"<span id='textarea_remaining'>2000 remaining</span>", max_length=2200, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='grievances',
            name='subject',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='grievances',
            name='user_closure_message',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
