# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 09:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompanyMaster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attdate', models.DateField(blank=True, null=True, verbose_name=b'Swipe Date')),
                ('swipe_in', models.DateTimeField(blank=True, null=True)),
                ('swipe_out', models.DateTimeField(blank=True, null=True)),
                ('incoming_employee_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name=b'Title')),
                ('billable', models.BooleanField(default=True, verbose_name=b'Billable')),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Qualification')),
                ('specialization', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Specialization')),
                ('nature_of_education', models.CharField(choices=[(b'FT', b'Full-time'), (b'PT', b'Part-time')], default=b'FT', max_length=2, verbose_name=b'Nature of Education')),
                ('from_date', models.DateField(verbose_name=b'From Date')),
                ('to_date', models.DateField(verbose_name=b'To Date')),
                ('institute', models.CharField(max_length=50, verbose_name=b'Institution')),
                ('overall_marks', models.IntegerField(verbose_name=b'Total Score/GPA')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='EmpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[(b'PR', b'Permanent'), (b'TM', b'Temporary')], default=b'TM', max_length=2, verbose_name=b'Address Type')),
                ('address1', models.CharField(max_length=100, verbose_name=b'Address 1')),
                ('address2', models.CharField(max_length=100, verbose_name=b'Address 2')),
                ('city', models.CharField(max_length=30, verbose_name=b'City')),
                ('state', models.CharField(max_length=30, verbose_name=b'State')),
                ('zipcode', models.CharField(max_length=10, verbose_name=b'Zip Code')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('middle_name', models.CharField(blank=True, max_length=15, verbose_name=b'Middle Name')),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=2, verbose_name=b'Gender')),
                ('date_of_birthO', models.DateField(default=None, verbose_name=b'Official DOB')),
                ('date_of_birthR', models.DateField(default=None, verbose_name=b'Alternate DOB')),
                ('nationality', models.CharField(max_length=30, verbose_name=b'Nationality')),
                ('marital_status', models.CharField(choices=[(b'MA', b'Married'), (b'WD', b'Windowed'), (b'SE', b'Seperated'), (b'DV', b'Divorced'), (b'SG', b'Single')], max_length=10, verbose_name=b'Marital Status')),
                ('wedding_date', models.DateField(blank=True, null=True, verbose_name=b'Wedding Date')),
                ('blood_group', models.CharField(blank=True, choices=[(b'00', b'A+'), (b'01', b'A-'), (b'02', b'B+'), (b'03', b'B-'), (b'04', b'O+'), (b'05', b'O-'), (b'06', b'AB+'), (b'07', b'AB-')], max_length=3, verbose_name=b'Blood Group')),
                ('mobile_phone', models.CharField(blank=True, max_length=15, unique=True, verbose_name=b'Mobile Phone')),
                ('land_phone', models.CharField(blank=True, max_length=15, verbose_name=b'Landline Number')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name=b'Emergency Contact Number')),
                ('personal_email', models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name=b'Personal E-mail')),
                ('passport_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name=b'Passport Number')),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=b'employee/emp_photo'), upload_to=b'', verbose_name=b'Employee Photo')),
                ('employee_assigned_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name=b'Employee ID')),
                ('idcard', models.CharField(max_length=15, unique=True, verbose_name=b'Access Card Number')),
                ('category', models.CharField(choices=[(b'FT', b'Fulltime Employee'), (b'PT', b'Parttime Employee'), (b'IN', b'Intern'), (b'CT', b'Contractor')], max_length=3, verbose_name=b'Employment Category')),
                ('exprience', models.IntegerField(verbose_name=b'Experience in Months')),
                ('color', models.CharField(blank=True, choices=[(b'violet', b'Violet'), (b'indigo', b'Indigo'), (b'blue', b'Blue'), (b'green', b'Green'), (b'yellow', b'Yellow'), (b'orange', b'Orange'), (b'red', b'Red')], max_length=10, null=True, verbose_name=b'Color')),
                ('joined', models.DateField(verbose_name=b'Joining Date')),
                ('confirmation', models.DateField(verbose_name=b'Confirmation Date')),
                ('last_promotion', models.DateField(verbose_name=b'Probation End Date')),
                ('resignation', models.DateField(blank=True, null=True, verbose_name=b'Resignation Date')),
                ('exit', models.DateField(blank=True, null=True, verbose_name=b'Exit Date')),
                ('PAN', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name=b'PAN Number')),
                ('PF_number', models.CharField(blank=True, max_length=14, verbose_name=b'Provident Fund Number')),
                ('uan', models.IntegerField(blank=True, null=True, unique=True, verbose_name=b'Universal account number')),
                ('bank_name', models.CharField(blank=True, max_length=70, null=True, verbose_name=b'Bank Name')),
                ('bank_branch', models.CharField(blank=True, max_length=70, null=True, verbose_name=b'Branch Name')),
                ('bank_account', models.IntegerField(blank=True, null=True, unique=True, verbose_name=b'Account Number')),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'IFSC Code')),
                ('group_insurance_number', models.CharField(blank=True, max_length=30, verbose_name=b'Group Insurance Number')),
                ('esi_number', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'ESI Number')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.BusinessUnit')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Designation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.OfficeLocation')),
                ('manager', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to='employee.Employee', verbose_name=b'Manager')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Name')),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'M', max_length=1, verbose_name=b'Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name=b'DOB')),
                ('rela_type', models.CharField(choices=[(b'FA', b'Father'), (b'MO', b'Mother'), (b'SP', b'Spouse'), (b'C1', b'Child1'), (b'C2', b'Child2'), (b'OO', b'Others')], max_length=50, verbose_name=b'Relation Type')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousEmployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name=b'Company Name')),
                ('company_address', models.CharField(max_length=500, verbose_name=b'Company Address')),
                ('employed_from', models.DateField(verbose_name=b'Start Date')),
                ('employed_upto', models.DateField(verbose_name=b'End Date')),
                ('pf_number', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'PF Number')),
                ('last_ctc', models.DecimalField(decimal_places=2, max_digits=15, verbose_name=b'Last CTC')),
                ('reason_for_exit', models.CharField(max_length=50, verbose_name=b'Reason for Exit')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Previous Employment',
                'verbose_name_plural': 'Previous Employment',
            },
        ),
        migrations.CreateModel(
            name='Remainder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Event Name')),
                ('startDate', models.DateField(default=django.utils.timezone.now, verbose_name=b'Start Date')),
                ('endDate', models.DateField(default=django.utils.timezone.now, verbose_name=b'End Date')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('employee', 'attdate')]),
        ),
    ]
