# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyMaster', '0002_auto_20170103_1446'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attdate', models.DateField(blank=True, null=True, verbose_name=b'Swipe Date')),
                ('swipe_in', models.DateTimeField(blank=True, null=True)),
                ('swipe_out', models.DateTimeField(blank=True, null=True)),
                ('incoming_employee_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompanyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('createdby', models.CharField(max_length=20, verbose_name=b'Created By')),
                ('updatedby', models.CharField(max_length=20, verbose_name=b'Updated By')),
                ('is_billable', models.BooleanField(default=True, verbose_name=b'Is Billable')),
                ('billable_date', models.DateField(blank=True, null=True, verbose_name=b'Effective Date of Billability')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Company', verbose_name=b'Company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Department', verbose_name=b'Department')),
            ],
            options={
                'verbose_name': 'Employee Company Information',
                'verbose_name_plural': 'Employees Company Information',
            },
        ),
        migrations.CreateModel(
            name='Remainder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Event Name')),
                ('startDate', models.DateField(default=django.utils.timezone.now, verbose_name=b'Start Date')),
                ('endDate', models.DateField(default=django.utils.timezone.now, verbose_name=b'End Date')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='division',
        ),
        migrations.AddField(
            model_name='designation',
            name='active',
            field=models.BooleanField(default=True, verbose_name=b'Is Active?'),
        ),
        migrations.AddField(
            model_name='education',
            name='nature_of_education',
            field=models.CharField(choices=[(b'FT', b'Full-time'), (b'PT', b'Part-time')], default=b'FT', max_length=2, verbose_name=b'Nature of Education'),
        ),
        migrations.AddField(
            model_name='education',
            name='specialization',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Specialization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='color',
            field=models.CharField(blank=True, choices=[(b'violet', b'Violet'), (b'indigo', b'Indigo'), (b'blue', b'Blue'), (b'green', b'Green'), (b'yellow', b'Yellow'), (b'orange', b'Orange'), (b'red', b'Red')], max_length=10, null=True, verbose_name=b'Color'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birthO',
            field=models.DateField(default=None, verbose_name=b'Official DOB'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birthR',
            field=models.DateField(blank=True, null=True, verbose_name=b'Alternate DOB'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to='employee.Employee', verbose_name=b'Manager'),
        ),
        migrations.AddField(
            model_name='employee',
            name='uan',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name=b'Universal account number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='wedding_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Wedding Date'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'M', max_length=1, verbose_name=b'Gender'),
        ),
        migrations.AlterField(
            model_name='education',
            name='overall_marks',
            field=models.IntegerField(verbose_name=b'Total Score/GPA'),
        ),
        migrations.AlterField(
            model_name='empaddress',
            name='address1',
            field=models.CharField(max_length=100, verbose_name=b'Address 1'),
        ),
        migrations.AlterField(
            model_name='empaddress',
            name='address2',
            field=models.CharField(max_length=100, verbose_name=b'Address 2'),
        ),
        migrations.AlterField(
            model_name='empaddress',
            name='city',
            field=models.CharField(max_length=30, verbose_name=b'City'),
        ),
        migrations.AlterField(
            model_name='empaddress',
            name='state',
            field=models.CharField(max_length=30, verbose_name=b'State'),
        ),
        migrations.AlterField(
            model_name='empaddress',
            name='zipcode',
            field=models.CharField(max_length=10, verbose_name=b'Zip Code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PAN',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name=b'PAN Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name=b'Account Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name=b'Branch Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'IFSC Code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name=b'Bank Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name=b'Emergency Contact Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='exprience',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Experience in Months'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[(b'MA', b'Married'), (b'WD', b'Windowed'), (b'SE', b'Seperated'), (b'DV', b'Divorced'), (b'SG', b'Single')], max_length=10, null=True, verbose_name=b'Marital Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name=b'Personal E-mail'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name=b'DOB'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='rela_type',
            field=models.CharField(choices=[(b'FA', b'Father'), (b'MO', b'Mother'), (b'SP', b'Spouse'), (b'C1', b'Child1'), (b'C2', b'Child2'), (b'OO', b'Others')], max_length=50, verbose_name=b'Relation Type'),
        ),
        migrations.AddField(
            model_name='remainder',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='employeecompanyinformation',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Designation', verbose_name=b'Designation'),
        ),
        migrations.AddField(
            model_name='employeecompanyinformation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name=b'Employee'),
        ),
        migrations.AddField(
            model_name='employeecompanyinformation',
            name='pnl',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.PnL', verbose_name=b'PnL'),
        ),
        migrations.AddField(
            model_name='employeecompanyinformation',
            name='practice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Practice', verbose_name=b'Practice'),
        ),
        migrations.AddField(
            model_name='employeecompanyinformation',
            name='sub_practice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.SubPractice', verbose_name=b'Sub Practice'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('employee', 'attdate')]),
        ),
    ]
