# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 09:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompanyMaster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Activity')),
                ('code', models.CharField(default=None, max_length=1, unique=True, verbose_name=b'Short Code')),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Name')),
                ('author', models.CharField(max_length=100, verbose_name=b'Author')),
                ('edition', models.CharField(blank=True, max_length=30, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name=b'ISBN')),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='BTGReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btg', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'BTG')),
                ('btgMonth', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name=b'BTG')),
                ('btgYear', models.IntegerField(default=1990, validators=[django.core.validators.MinValueValidator(1990)], verbose_name=b'BTG')),
                ('currMonthRR', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('currMonthIN', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Number Of Invoices')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Name')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name=b'Project Name')),
                ('customerContact', models.CharField(default=None, max_length=100, verbose_name=b'Customer Contact')),
                ('currentProject', models.BooleanField(default=True, verbose_name=b'New Development')),
                ('signed', models.BooleanField(default=True, verbose_name=b'Contract Signed')),
                ('internal', models.BooleanField(default=False, verbose_name=b'Internal Project')),
                ('projectId', models.CharField(max_length=60, unique=True, verbose_name=b'Project Code')),
                ('po', models.CharField(default=0, max_length=60, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z-]*$', b'Only alphanumeric characters are allowed.')], verbose_name=b'P.O.')),
                ('startDate', models.DateField(default=django.utils.timezone.now, verbose_name=b'Project Start Date')),
                ('endDate', models.DateField(default=django.utils.timezone.now, verbose_name=b'Project End Date')),
                ('salesForceNumber', models.IntegerField(default=0, help_text=b'8 digit number starting with 201', validators=[django.core.validators.MinValueValidator(20100000), django.core.validators.MaxValueValidator(99999999)], verbose_name=b'SF                                           Opportunity Number')),
                ('plannedEffort', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Planned Effort')),
                ('contingencyEffort', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Contigency Effort')),
                ('totalValue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'Total Value')),
                ('closed', models.BooleanField(default=False, verbose_name=b'Project Closed')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Book', verbose_name=b'Book/Title')),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.BusinessUnit', verbose_name=b'Business Unit')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Customer', verbose_name=b'Customer')),
            ],
            options={
                'permissions': (('create_project', 'Create ANSR projects'), ('manage_project', 'Manage ANSR Project'), ('approve_timesheet', 'Approve timesheets'), ('manage_milestones', 'Manage Project Milestones'), ('view_all_projects', 'View all projects'), ('view_all_reports', 'View All Reports')),
            },
        ),
        migrations.CreateModel(
            name='ProjectChangeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crId', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name=b'Change Request ID')),
                ('reason', models.CharField(default=None, max_length=100, verbose_name=b'Reason for change')),
                ('endDate', models.DateField(default=None, verbose_name=b'Revised Project End Date')),
                ('po', models.CharField(default=0, max_length=60, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z-]*$', b'Only alphanumeric characters are allowed.')], verbose_name=b'P.O.')),
                ('revisedEffort', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Revised Effort')),
                ('revisedTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Revised amount')),
                ('salesForceNumber', models.IntegerField(default=0, help_text=b'8 digit number starting with 201', validators=[django.core.validators.MinValueValidator(20100000), django.core.validators.MaxValueValidator(99999999)], verbose_name=b'Sales Force                                            Opportunity Number')),
                ('closed', models.BooleanField(default=False, verbose_name=b'Close the Project')),
                ('closedOn', models.DateTimeField(blank=True, default=None, null=True)),
                ('signed', models.BooleanField(default=False, verbose_name=b'Contract Signed')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project', verbose_name=b'Project Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestoneDate', models.DateField(default=django.utils.timezone.now, verbose_name=b'Milestone Date')),
                ('description', models.CharField(default=None, max_length=1000, null=True, verbose_name=b'Description')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Amount')),
                ('closed', models.BooleanField(default=False, verbose_name=b'Completed')),
                ('closedon', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name=b'Closed On')),
                ('financial', models.BooleanField(default=False, verbose_name=b'Financial')),
                ('reason', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name=b'Reason for change')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name=b'Start date on project')),
                ('endDate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name=b'End date on project')),
                ('plannedEffort', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name=b'Planned Effort')),
                ('rate', models.IntegerField(blank=True, default=100, verbose_name=b'%')),
                ('active', models.BooleanField(default=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('datapoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.DataPoint', verbose_name='Service Line')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project')),
            ],
        ),
        migrations.CreateModel(
            name='projectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name=b'Unit of Work')),
                ('description', models.CharField(max_length=100, verbose_name=b'Description')),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'nonclosedprojectts', b'Non Closed Project TS')], default=b'nonclosedprojectts', max_length=50, verbose_name=b'Report')),
                ('freq', models.CharField(choices=[(b'M', b'Monthly'), (b'W', b'Weekly')], default=b'W', max_length=2, verbose_name=b'Frequency')),
                ('day', models.IntegerField(choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10), (10, 11), (11, 12), (12, 13), (13, 14), (14, 15), (15, 16), (16, 17), (17, 18), (18, 19), (19, 20), (20, 21), (21, 22), (22, 23), (23, 24), (24, 25), (25, 26), (26, 27), (27, 28), (28, 29), (29, 30)], default=0, verbose_name=b'Day')),
                ('weekday', models.IntegerField(choices=[(0, b'Monday'), (1, b'Tuesday'), (2, b'Wednesday'), (3, b'Thursday'), (4, b'Friday'), (5, b'Saturday'), (6, b'Sunday')], default=0, verbose_name=b'Weekday')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('notify', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name=b'Notifier(s)')),
            ],
        ),
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toAddr', models.CharField(default=None, max_length=1000)),
                ('template_name', models.CharField(default=None, max_length=100)),
                ('content', models.CharField(default=None, max_length=1000)),
                ('sent', models.BooleanField(default=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Task')),
                ('code', models.CharField(default=None, max_length=1, verbose_name=b'Short Code')),
                ('taskType', models.CharField(choices=[(b'B', b'Revenue'), (b'I', b'Idle'), (b'N', b'Non-Revenue')], default=None, max_length=2, verbose_name=b'Task type')),
                ('norm', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'Norm')),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('projectType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.projectType', verbose_name=b'Project Type')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkstart', models.DateField(blank=True, default=None, verbose_name=b'Week Start')),
                ('wkend', models.DateField(blank=True, default=None, verbose_name=b'Week End')),
                ('mondayQ', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Mon')),
                ('mondayH', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Mon')),
                ('tuesdayQ', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Tue')),
                ('tuesdayH', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Tue')),
                ('wednesdayQ', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Wed')),
                ('wednesdayH', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Wed')),
                ('thursdayQ', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Thu')),
                ('thursdayH', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Thu')),
                ('fridayQ', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Fri')),
                ('fridayH', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Fri')),
                ('saturdayQ', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Sat')),
                ('saturdayH', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Sat')),
                ('sundayQ', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Sun')),
                ('sundayH', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Sun')),
                ('totalQ', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Total')),
                ('totalH', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Total')),
                ('approved', models.BooleanField(default=False)),
                ('hold', models.BooleanField(default=False)),
                ('approvedon', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name=b'Approved On')),
                ('managerFeedback', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name=b'Manager Feedback')),
                ('exception', models.CharField(default=b'No Exception', max_length=75)),
                ('billable', models.BooleanField(default=False, verbose_name=b'Billable')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Activity', verbose_name=b'Activity')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Chapter', verbose_name=b'Chapter/Subtitle')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.OfficeLocation', verbose_name=b'Location')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project', verbose_name=b'Project Name')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Task', verbose_name=b'Task')),
                ('teamMember', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timesheet Entry',
                'verbose_name_plural': 'Timesheet Entries',
                'permissions': (('enter_timesheet', 'Allow timetracking'),),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='projectManager',
            field=models.ManyToManyField(through='MyANSRSource.ProjectManager', to=settings.AUTH_USER_MODEL, verbose_name=b'Project Leader'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.projectType', verbose_name=b'Project Type'),
        ),
        migrations.AddField(
            model_name='btgreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project', verbose_name=b'Project Name'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('name', 'edition', 'author')]),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('projectType', 'name'), ('projectType', 'code')]),
        ),
    ]
