# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    replaces = [(b'MyANSRSource', '0001_initial'), (b'MyANSRSource', '0002_auto_20150109_1656'), (b'MyANSRSource', '0003_auto_20150109_1801'), (b'MyANSRSource', '0004_auto_20150114_1138'), (b'MyANSRSource', '0005_auto_20150114_1535'), (b'MyANSRSource', '0006_auto_20150115_0940'), (b'MyANSRSource', '0007_book_author'), (b'MyANSRSource', '0007_auto_20150115_2308'), (b'MyANSRSource', '0008_merge'), (b'MyANSRSource', '0009_auto_20150122_2155'), (b'MyANSRSource', '0010_auto_20150201_1052'), (b'MyANSRSource', '0011_auto_20150203_1157'), (b'MyANSRSource', '0012_auto_20150204_1111'), (b'MyANSRSource', '0013_project_maxproductivityunits'), (b'MyANSRSource', '0011_auto_20150206_1716'), (b'MyANSRSource', '0014_merge'), (b'MyANSRSource', '0015_merge'), (b'MyANSRSource', '0016_auto_20150209_1229'), (b'MyANSRSource', '0017_timesheetentry_toapprove'), (b'MyANSRSource', '0018_auto_20150210_1103'), (b'MyANSRSource', '0019_remove_timesheetentry_toapprove'), (b'MyANSRSource', '0020_auto_20150214_0701')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyMaster', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'Book Name')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'Chapter Name')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('book', models.ForeignKey(to='MyANSRSource.Book')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('projectType', models.CharField(default=b'Q', max_length=2, verbose_name=b'Project Type', choices=[(b'Q', b'Questions'), (b'P', b'Powerpoint'), (b'I', b'Instructional')])),
                ('name', models.CharField(max_length=50, verbose_name=b'Project Name')),
                ('currentProject', models.BooleanField(default=True, verbose_name=b'Project Stage')),
                ('signed', models.BooleanField(default=True, verbose_name=b'Contact Signed')),
                ('internal', models.BooleanField(default=True, verbose_name=b'Internal Project')),
                ('projectId', models.CharField(max_length=60)),
                ('startDate', models.DateTimeField(verbose_name=b'Project Start Date')),
                ('endDate', models.DateTimeField(verbose_name=b'Project End Date')),
                ('plannedEffort', models.IntegerField(default=0, verbose_name=b'Planned Effort')),
                ('contingencyEffort', models.IntegerField(default=0, verbose_name=b'Contigency Effort')),
                ('totalValue', models.IntegerField(default=0, verbose_name=b'Total Value')),
                ('closed', models.BooleanField(default=False, verbose_name=b'Project Closed')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('book', models.ForeignKey(default=None, verbose_name=b'Book', to='MyANSRSource.Book')),
                ('bu', models.ForeignKey(verbose_name=b'Business Unit', to='CompanyMaster.BusinessUnit')),
                ('chapters', models.ManyToManyField(to=b'MyANSRSource.Chapter')),
                ('customer', models.ForeignKey(default=None, verbose_name=b'Customer', to='CompanyMaster.Customer')),
                ('projectManager', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProjectChangeInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('crId', models.CharField(default=None, max_length=100, null=True, verbose_name=b'Change Request ID', blank=True)),
                ('reason', models.CharField(default=None, max_length=100, verbose_name=b'Reason for change', blank=True)),
                ('endDate', models.DateField(default=None, verbose_name=b'Revised Project End Date')),
                ('revisedEffort', models.IntegerField(default=0, verbose_name=b'Revised Effort')),
                ('revisedTotal', models.DecimalField(default=0, verbose_name=b'Revised amount', max_digits=12, decimal_places=2)),
                ('closed', models.BooleanField(default=False, verbose_name=b'Close the Project')),
                ('closedOn', models.DateField(default=None, null=True, blank=True)),
                ('signed', models.BooleanField(default=False, verbose_name=b'Contract Signed')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('project', models.ForeignKey(verbose_name=b'Project Name', to='MyANSRSource.Project')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('milestoneDate', models.DateField(default=django.utils.timezone.now, verbose_name=b'Milestone Date')),
                ('description', models.CharField(default=None, max_length=1000, null=True, verbose_name=b'Description')),
                ('amount', models.DecimalField(default=0, verbose_name=b'Amount', max_digits=12, decimal_places=2)),
                ('closed', models.BooleanField(default=False, verbose_name=b'Completed')),
                ('reason', models.CharField(default=None, max_length=100, null=True, verbose_name=b'Reason for change', blank=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('project', models.ForeignKey(to='MyANSRSource.Project')),
                ('financial', models.BooleanField(default=False, verbose_name=b'Financial')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('startDate', models.DateField(default=django.utils.timezone.now, verbose_name=b'Start date on project', blank=True)),
                ('endDate', models.DateField(default=django.utils.timezone.now, verbose_name=b'End date on project', blank=True)),
                ('plannedEffort', models.IntegerField(default=0, verbose_name=b'Planned Effort', blank=True)),
                ('rate', models.IntegerField(default=100, verbose_name=b'%', blank=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('member', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('project', models.ForeignKey(to='MyANSRSource.Project')),
                ('role', models.ForeignKey(default=None, blank=True, to='employee.Designation', null=True, verbose_name=b'Role')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TimeSheetEntry',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('wkstart', models.DateField(default=None, verbose_name=b'Week Start', blank=True)),
                ('wkend', models.DateField(default=None, verbose_name=b'Week End', blank=True)),
                ('activity', models.CharField(max_length=2, null=True)),
                ('task', models.CharField(max_length=2, null=True)),
                ('mondayQ', models.IntegerField(default=0, verbose_name=b'Mon')),
                ('mondayH', models.IntegerField(default=0, verbose_name=b'Mon')),
                ('tuesdayQ', models.IntegerField(default=0, verbose_name=b'Tue')),
                ('tuesdayH', models.IntegerField(default=0, verbose_name=b'Tue')),
                ('wednesdayQ', models.IntegerField(default=0, verbose_name=b'Wed')),
                ('wednesdayH', models.IntegerField(default=0, verbose_name=b'Wed')),
                ('thursdayQ', models.IntegerField(default=0, verbose_name=b'Thu')),
                ('thursdayH', models.IntegerField(default=0, verbose_name=b'Thu')),
                ('fridayQ', models.IntegerField(default=0, verbose_name=b'Fri')),
                ('fridayH', models.IntegerField(default=0, verbose_name=b'Fri')),
                ('saturdayQ', models.IntegerField(default=0, verbose_name=b'Sat')),
                ('saturdayH', models.IntegerField(default=0, verbose_name=b'Sat')),
                ('sundayQ', models.IntegerField(default=0, verbose_name=b'Sun')),
                ('sundayH', models.IntegerField(default=0, verbose_name=b'Sun')),
                ('totalQ', models.IntegerField(default=0, verbose_name=b'Total')),
                ('totalH', models.IntegerField(default=0, verbose_name=b'Total')),
                ('approved', models.BooleanField(default=False)),
                ('hold', models.BooleanField(default=False)),
                ('approvedon', models.DateTimeField(default=None, verbose_name=b'Approved On', null=True, editable=False, blank=True)),
                ('managerFeedback', models.CharField(default=None, max_length=1000, null=True, verbose_name=b'Manager Feedback', blank=True)),
                ('exception', models.CharField(default=b'No Exception', max_length=75)),
                ('billable', models.BooleanField(default=False, verbose_name=b'Billable')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('chapter', models.ForeignKey(verbose_name=b'Chapter', to='MyANSRSource.Chapter', null=True)),
                ('location', models.ForeignKey(verbose_name=b'Location', to='CompanyMaster.OfficeLocation', null=True)),
                ('project', models.ForeignKey(verbose_name=b'Project Name', to='MyANSRSource.Project', null=True)),
                ('teamMember', models.ForeignKey(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timesheet Entry',
                'verbose_name_plural': 'Timesheet Entries',
            },
            bases=(models.Model,),
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('manage_project', 'Create/Manage ANSR Project'), ('approve_timesheet', 'Approve timesheets'), ('manage_milestones', 'Manage Project Milestones'))},
        ),
        migrations.AlterModelOptions(
            name='timesheetentry',
            options={'verbose_name': 'Timesheet Entry', 'verbose_name_plural': 'Timesheet Entries', 'permissions': (('enter_timesheet', 'Allow timetracking'),)},
        ),
        migrations.AlterField(
            model_name='project',
            name='internal',
            field=models.BooleanField(default=False, verbose_name=b'Internal Project'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateField(verbose_name=b'Project End Date'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(verbose_name=b'Project Start Date'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='--To be Provided--', max_length=100, verbose_name=b'Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='totalValue',
            field=models.DecimalField(default=0, verbose_name=b'Total Value', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.CreateModel(
            name='projectType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=2, verbose_name=b'Unit of Work')),
                ('description', models.CharField(max_length=100, verbose_name=b'Description')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.ForeignKey(verbose_name=b'Project Type', to='MyANSRSource.projectType'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='fridayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Fri', max_digits=12, decimal_places=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='mondayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Mon', max_digits=12, decimal_places=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='saturdayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Sat', max_digits=12, decimal_places=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='sundayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Sun', max_digits=12, decimal_places=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='thursdayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Thu', max_digits=12, decimal_places=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='totalQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Total', max_digits=12, decimal_places=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='tuesdayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Tue', max_digits=12, decimal_places=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='wednesdayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Wed', max_digits=12, decimal_places=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='fridayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Fri', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='mondayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Mon', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='saturdayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Sat', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='sundayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Sun', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='thursdayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Thu', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='totalQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Total', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='tuesdayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Tue', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='wednesdayQ',
            field=models.DecimalField(default=0.0, verbose_name=b'Wed', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='maxProductivityUnits',
            field=models.DecimalField(default=0.0, verbose_name=b'Norm', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'Name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='project',
            name='signed',
            field=models.BooleanField(default=True, verbose_name=b'Contract Signed'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='fridayH',
            field=models.DecimalField(default=0.0, verbose_name=b'Fri', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='mondayH',
            field=models.DecimalField(default=0.0, verbose_name=b'Mon', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='saturdayH',
            field=models.DecimalField(default=0.0, verbose_name=b'Sat', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='sundayH',
            field=models.DecimalField(default=0.0, verbose_name=b'Sun', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='thursdayH',
            field=models.DecimalField(default=0.0, verbose_name=b'Thu', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='totalH',
            field=models.DecimalField(default=0.0, verbose_name=b'Total', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='tuesdayH',
            field=models.DecimalField(default=0.0, verbose_name=b'Tue', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='wednesdayH',
            field=models.DecimalField(default=0.0, verbose_name=b'Wed', max_digits=12, decimal_places=2),
            preserve_default=True,
        ),
    ]
