# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 09:16
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyMaster', '0002_auto_20170103_1446'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyANSRSource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Activity')),
                ('code', models.CharField(default=None, max_length=1, unique=True, verbose_name=b'Short Code')),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='BTGReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btg', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'BTG')),
                ('btgMonth', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name=b'BTG')),
                ('btgYear', models.IntegerField(default=1990, validators=[django.core.validators.MinValueValidator(1990)], verbose_name=b'BTG')),
                ('currMonthRR', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('currMonthIN', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Number Of Invoices')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='projectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name=b'Unit of Work')),
                ('description', models.CharField(max_length=100, verbose_name=b'Description')),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'nonclosedprojectts', b'Non Closed Project TS')], default=b'nonclosedprojectts', max_length=50, verbose_name=b'Report')),
                ('freq', models.CharField(choices=[(b'M', b'Monthly'), (b'W', b'Weekly')], default=b'W', max_length=2, verbose_name=b'Frequency')),
                ('day', models.IntegerField(choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10), (10, 11), (11, 12), (12, 13), (13, 14), (14, 15), (15, 16), (16, 17), (17, 18), (18, 19), (19, 20), (20, 21), (21, 22), (22, 23), (23, 24), (24, 25), (25, 26), (26, 27), (27, 28), (28, 29), (29, 30)], default=0, verbose_name=b'Day')),
                ('weekday', models.IntegerField(choices=[(0, b'Monday'), (1, b'Tuesday'), (2, b'Wednesday'), (3, b'Thursday'), (4, b'Friday'), (5, b'Saturday'), (6, b'Sunday')], default=0, verbose_name=b'Weekday')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('notify', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name=b'Notifier(s)')),
            ],
        ),
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toAddr', models.CharField(default=None, max_length=1000)),
                ('template_name', models.CharField(default=None, max_length=100)),
                ('content', models.CharField(default=None, max_length=1000)),
                ('sent', models.BooleanField(default=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Task')),
                ('code', models.CharField(default=None, max_length=1, verbose_name=b'Short Code')),
                ('taskType', models.CharField(choices=[(b'B', b'Revenue'), (b'I', b'Idle'), (b'N', b'Non-Revenue')], default=None, max_length=2, verbose_name=b'Task type')),
                ('norm', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'Norm')),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('projectType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.projectType', verbose_name=b'Project Type')),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('create_project', 'Create ANSR projects'), ('manage_project', 'Manage ANSR Project'), ('approve_timesheet', 'Approve timesheets'), ('manage_milestones', 'Manage Project Milestones'), ('view_all_projects', 'View all projects'), ('view_all_reports', 'View All Reports'))},
        ),
        migrations.AlterModelOptions(
            name='timesheetentry',
            options={'permissions': (('enter_timesheet', 'Allow timetracking'),), 'verbose_name': 'Timesheet Entry', 'verbose_name_plural': 'Timesheet Entries'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='projectteammember',
            name='role',
        ),
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=True, verbose_name=b'Is Active?'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=100, verbose_name=b'Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name=b'ISBN'),
        ),
        migrations.AddField(
            model_name='project',
            name='customerContact',
            field=models.CharField(default=None, max_length=100, verbose_name=b'Customer Contact'),
        ),
        migrations.AddField(
            model_name='project',
            name='po',
            field=models.CharField(default=0, max_length=60, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z-]*$', b'Only alphanumeric characters are allowed.')], verbose_name=b'P.O.'),
        ),
        migrations.AddField(
            model_name='project',
            name='salesForceNumber',
            field=models.IntegerField(default=0, help_text=b'8 digit number starting with 201', validators=[django.core.validators.MinValueValidator(20100000), django.core.validators.MaxValueValidator(99999999)], verbose_name=b'SF                                           Opportunity Number'),
        ),
        migrations.AddField(
            model_name='projectchangeinfo',
            name='po',
            field=models.CharField(default=0, max_length=60, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z-]*$', b'Only alphanumeric characters are allowed.')], verbose_name=b'P.O.'),
        ),
        migrations.AddField(
            model_name='projectchangeinfo',
            name='salesForceNumber',
            field=models.IntegerField(default=0, help_text=b'8 digit number starting with 201', validators=[django.core.validators.MinValueValidator(20100000), django.core.validators.MaxValueValidator(99999999)], verbose_name=b'Sales Force                                            Opportunity Number'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='closedon',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name=b'Closed On'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='financial',
            field=models.BooleanField(default=False, verbose_name=b'Financial'),
        ),
        migrations.AddField(
            model_name='projectteammember',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectteammember',
            name='datapoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.DataPoint', verbose_name='Service Line'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Book', verbose_name=b'Book/Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contingencyEffort',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Contigency Effort'),
        ),
        migrations.AlterField(
            model_name='project',
            name='currentProject',
            field=models.BooleanField(default=True, verbose_name=b'New Development'),
        ),
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=b'Project End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='internal',
            field=models.BooleanField(default=False, verbose_name=b'Internal Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name=b'Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='plannedEffort',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Planned Effort'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectId',
            field=models.CharField(max_length=60, unique=True, verbose_name=b'Project Code'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectManager',
        ),
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.projectType', verbose_name=b'Project Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='signed',
            field=models.BooleanField(default=True, verbose_name=b'Contract Signed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=b'Project Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='totalValue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'Total Value'),
        ),
        migrations.AlterField(
            model_name='projectchangeinfo',
            name='closedOn',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='projectchangeinfo',
            name='endDate',
            field=models.DateField(default=None, verbose_name=b'Revised Project End Date'),
        ),
        migrations.AlterField(
            model_name='projectchangeinfo',
            name='reason',
            field=models.CharField(default=None, max_length=100, verbose_name=b'Reason for change'),
        ),
        migrations.AlterField(
            model_name='projectchangeinfo',
            name='revisedEffort',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Revised Effort'),
        ),
        migrations.AlterField(
            model_name='projectchangeinfo',
            name='revisedTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Revised amount'),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Amount'),
        ),
        migrations.AlterField(
            model_name='projectteammember',
            name='endDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name=b'End date on project'),
        ),
        migrations.AlterField(
            model_name='projectteammember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectteammember',
            name='plannedEffort',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name=b'Planned Effort'),
        ),
        migrations.AlterField(
            model_name='projectteammember',
            name='rate',
            field=models.IntegerField(blank=True, default=100, verbose_name=b'%'),
        ),
        migrations.AlterField(
            model_name='projectteammember',
            name='startDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name=b'Start date on project'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Activity', verbose_name=b'Activity'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Chapter', verbose_name=b'Chapter/Subtitle'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='fridayH',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Fri'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='fridayQ',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Fri'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='mondayH',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Mon'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='mondayQ',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Mon'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='saturdayH',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Sat'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='saturdayQ',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Sat'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='sundayH',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Sun'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='sundayQ',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Sun'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Task', verbose_name=b'Task'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='thursdayH',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Thu'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='thursdayQ',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Thu'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='totalH',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Total'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='totalQ',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Total'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='tuesdayH',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Tue'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='tuesdayQ',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Tue'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='wednesdayH',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Wed'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='wednesdayQ',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Wed'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('name', 'edition', 'author')]),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='btgreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyANSRSource.Project', verbose_name=b'Project Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectManager',
            field=models.ManyToManyField(through='MyANSRSource.ProjectManager', to=settings.AUTH_USER_MODEL, verbose_name=b'Project Leader'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('projectType', 'name'), ('projectType', 'code')]),
        ),
    ]
