# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_clearance', models.BooleanField(verbose_name='hr clearance')),
                ('IT_clearance', models.BooleanField(verbose_name='it clearance')),
                ('manager_clearance', models.BooleanField(verbose_name='manager clearance')),
                ('admin_clearance', models.BooleanField(verbose_name='admin clearance')),
                ('library_clearance', models.BooleanField(verbose_name='Library clearance')),
                ('resign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_feedback', models.CharField(max_length=1000, verbose_name='HR comment over Employee')),
                ('manager_feedback', models.CharField(max_length=1000, verbose_name='Manger comment over Employee')),
                ('it_feedback', models.CharField(max_length=1000, verbose_name='IT comment over Employee')),
                ('library_feedback', models.CharField(max_length=1000, verbose_name='LIBRARY comment over Employee')),
                ('admin_feedback', models.CharField(max_length=1000, verbose_name='HR comment over Employee')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResignationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_reason', models.CharField(max_length=250, verbose_name='Reason')),
                ('hr_accepted', models.NullBooleanField(verbose_name='HR clearance')),
                ('manager_accepted', models.NullBooleanField(verbose_name='manager clearance')),
                ('last_date', models.DateTimeField(blank=True, verbose_name='Last Date Opted By employee')),
                ('last_date_accepted', models.DateTimeField(blank=True, null=True, verbose_name='Last Date Accepted By Organisation')),
                ('reason_optional', models.CharField(blank=True, max_length=1000, verbose_name='optional text area')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='updated on')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'Regignation info',
            },
        ),
    ]
