# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExitApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceinfo',
            name='resign',
        ),
        migrations.DeleteModel(
            name='ClearanceInfo',
        ),
    ]
