# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExitApp', '0002_auto_20161221_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_clearance', models.BooleanField(verbose_name='hr clearance')),
                ('IT_clearance', models.BooleanField(verbose_name='it clearance')),
                ('manager_clearance', models.BooleanField(verbose_name='manager clearance')),
                ('admin_clearance', models.BooleanField(verbose_name='admin clearance')),
                ('library_clearance', models.BooleanField(verbose_name='Library clearance')),
                ('resign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
