# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'booked', b'Booked'), (b'cancelled', b'Cancelled')], max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name=b'last')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[(b'karle_ground_floor', b'Karle-Ground Floor'), (b'karle_second_floor', b'Karle-Second Floor'), (b'btp', b'BTP')], max_length=100)),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
            ],
        ),
        migrations.AddField(
            model_name='meetingroombooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyRoom.RoomDetail'),
        ),
    ]
