# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompanyMaster', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Designation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.OfficeLocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
