# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 09:16
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_auto_20170103_1446'),
        ('fb360', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FB360',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name=b'Name')),
                ('start_date', models.DateField(verbose_name=b'Start 360 degree appraisal')),
                ('end_date', models.DateField(verbose_name=b'Complete 360 degree appraisal')),
                ('selection_date', models.DateField(verbose_name=b'Peer / Reportee / Additional Manager selection completion date')),
                ('approval_date', models.DateField(verbose_name=b'Peer / Reportee / Additional Manager approval completion date')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('eligible', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL, verbose_name=b'Eligible Person(s)')),
            ],
            options={
                'verbose_name': '360 degree Survey Information',
                'verbose_name_plural': '360 degree Survey Information',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Name')),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Priority')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('fb', models.ManyToManyField(default=None, related_name='New_FB', to='fb360.FB360')),
            ],
        ),
        migrations.CreateModel(
            name='Initiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='emp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_type', models.CharField(choices=[(b'P', b'Peer'), (b'E', b'Reportee'), (b'M', b'Manager'), (b'AM', b'Additional Manager')], default=b'P', max_length=2, verbose_name=b'Respondent Type')),
                ('status', models.CharField(choices=[(b'P', b'Pending'), (b'A', b'Approved'), (b'R', b'Rejected'), (b'D', b'Deleted')], default=b'P', max_length=1, verbose_name=b'Status')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Pempl', to=settings.AUTH_USER_MODEL, verbose_name=b'Respondent')),
                ('initiator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Pempl', to='fb360.Initiator', verbose_name=b'Initiator')),
            ],
        ),
        migrations.RemoveField(
            model_name='emppeer',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='emppeer',
            name='peer',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='qst',
        ),
        migrations.RemoveField(
            model_name='peer',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='peer',
            name='emppeer',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('category__name',)},
        ),
        migrations.RemoveField(
            model_name='question',
            name='ans',
        ),
        migrations.RemoveField(
            model_name='response',
            name='year',
        ),
        migrations.AddField(
            model_name='qualitativeresponse',
            name='qst',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fb360.Question'),
        ),
        migrations.AddField(
            model_name='qualitativeresponse',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='priority',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Priority'),
        ),
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[(b'Q', b'Qualitative'), (b'M', b'Multiple Choice')], default=b'Q', max_length=1, verbose_name=b'Type'),
        ),
        migrations.AddField(
            model_name='response',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(default=None, to='employee.Designation', verbose_name=b'Roles'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qst',
            field=models.CharField(max_length=256, verbose_name=b'Question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='ans',
            field=models.CharField(max_length=8),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='EmpPeer',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Peer',
        ),
        migrations.AddField(
            model_name='initiator',
            name='respondents',
            field=models.ManyToManyField(default=None, related_name='Epeer', through='fb360.Respondent', to=settings.AUTH_USER_MODEL, verbose_name=b'Choose Respondent'),
        ),
        migrations.AddField(
            model_name='initiator',
            name='survey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fb360.FB360'),
        ),
        migrations.AddField(
            model_name='qualitativeresponse',
            name='fb',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb360.FB360'),
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ManyToManyField(default=None, related_name='New_Group', to='fb360.Group'),
        ),
        migrations.AddField(
            model_name='response',
            name='fb',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb360.FB360'),
        ),
        migrations.AlterUniqueTogether(
            name='respondent',
            unique_together=set([('employee', 'initiator', 'respondent_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='initiator',
            unique_together=set([('employee', 'survey')]),
        ),
    ]
