# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_reason',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_status',
        ),
    ]
