# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-13 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name=b'Business Unit Name')),
                ('centerType', models.CharField(choices=[(b'P', b'Profit Center'), (b'C', b'Cost Center')], default=None, max_length=2, verbose_name=b'Type of center')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('new_bu_head', models.ManyToManyField(blank=True, related_name='New_BU_Head', to=settings.AUTH_USER_MODEL, verbose_name=b'Business Unit Head')),
            ],
        ),
        migrations.CreateModel(
            name='CareerBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name=b'Career Band Code')),
                ('description', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Career Band Name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
            ],
            options={
                'verbose_name': 'Career Band',
                'verbose_name_plural': 'Career Bands',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('company_name', models.CharField(max_length=40, verbose_name=b'company name')),
                ('company_legal_name', models.CharField(max_length=50, verbose_name=b'company legal name')),
                ('legal_HQ_address', models.TextField(blank=True, null=True, verbose_name=b'legal head quarter address')),
                ('legal_HQ_city', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'legal head quarter city')),
                ('legal_HQ_state', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'legal head quarter state')),
                ('legal_HQ_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'legal head quarter zipcode')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('country_code', models.CharField(max_length=20, unique=True, verbose_name=b'Country Code')),
                ('country_name', models.CharField(max_length=50, verbose_name=b'Country Name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('privacy_rule', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Privacy Rule')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('currency_code', models.CharField(max_length=10, unique=True, verbose_name=b'currency code')),
                ('currency_name', models.CharField(max_length=50, verbose_name=b'currency name')),
                ('default', models.BooleanField(default=True, verbose_name=b'Default')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name=b'Customer Name')),
                ('internal', models.BooleanField(default=False, verbose_name=b'Internal Customer')),
                ('customerCode', models.CharField(default=None, max_length=3, verbose_name=b'Customer Code')),
                ('location', models.CharField(default=None, max_length=100, verbose_name=b'Location')),
                ('seqNumber', models.PositiveIntegerField(default=1, verbose_name=b'Project ID Sequence')),
                ('cContact', models.CharField(default=None, max_length=100, verbose_name=b'Customer contact')),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('address', models.CharField(default=None, max_length=100, verbose_name=b'Address')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('customer_group_code', models.CharField(max_length=20, unique=True, verbose_name=b'customer group code')),
                ('customer_group_name', models.CharField(max_length=50, verbose_name=b'customer group name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
            ],
            options={
                'verbose_name': 'Customer Group',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'Type of Customer')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name=b'Service Line')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.BusinessUnit', verbose_name=b'BU')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Lead')),
            ],
            options={
                'verbose_name': 'Service Line',
                'verbose_name_plural': 'Service Lines',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('createdby', models.CharField(max_length=20, verbose_name=b'Created By')),
                ('updatedby', models.CharField(max_length=20, verbose_name=b'Updated By')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name=b'Department Code')),
                ('name', models.CharField(max_length=40, verbose_name=b'Department Name')),
                ('billable', models.BooleanField(verbose_name=b'Is Billable')),
                ('practices', models.BooleanField(verbose_name=b'Has Practices')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Department Head')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('createdby', models.CharField(max_length=20, verbose_name=b'Created By')),
                ('updatedby', models.CharField(max_length=20, verbose_name=b'Updated By')),
                ('name', models.CharField(max_length=40, verbose_name=b'Designation Name')),
                ('is_active', models.BooleanField(verbose_name=b'Is Active')),
                ('steps', models.IntegerField(verbose_name=b'Ladder Step')),
                ('career_band_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.CareerBand')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name=b'Sub Department Name')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Holiday Name')),
                ('date', models.DateField(verbose_name=b'Holiday Date')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('remark', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name=b'remark')),
            ],
        ),
        migrations.CreateModel(
            name='HRActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name=b'Event Name')),
                ('date', models.DateField(verbose_name=b'Event Date')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
            options={
                'verbose_name': 'HR Activity',
                'verbose_name_plural': 'HR Activities',
            },
        ),
        migrations.CreateModel(
            name='KRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('createdby', models.CharField(max_length=20, verbose_name=b'Created By')),
                ('updatedby', models.CharField(max_length=20, verbose_name=b'Updated By')),
                ('series', models.IntegerField()),
                ('narration', models.TextField(verbose_name=b'KRA Narration')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Designation')),
            ],
            options={
                'verbose_name': 'KRA',
                'verbose_name_plural': 'KRAs',
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'Location Name')),
                ('city', models.CharField(max_length=15, verbose_name=b'City')),
                ('state', models.CharField(max_length=20, verbose_name=b'State')),
                ('zipcode', models.CharField(max_length=6, verbose_name=b'ZIP or PIN code ')),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='PnL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name=b'PnL Name')),
                ('description', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'PnL Description')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PNL',
                'verbose_name_plural': 'PNLS',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('createdby', models.CharField(max_length=20, verbose_name=b'Created By')),
                ('updatedby', models.CharField(max_length=20, verbose_name=b'Updated By')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name=b'Practice Code')),
                ('name', models.CharField(max_length=40, verbose_name=b'Practice Name')),
                ('sub_practice', models.BooleanField(verbose_name=b'Has Sub Practice')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Department')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice',
                'verbose_name_plural': 'Practices',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('createdby', models.CharField(max_length=20, verbose_name=b'Created By')),
                ('updatedby', models.CharField(max_length=20, verbose_name=b'Updated By')),
                ('region_code', models.CharField(max_length=10, unique=True, verbose_name=b'region code')),
                ('region_name', models.CharField(max_length=50, verbose_name=b'region name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name=b'Role Code')),
                ('name', models.CharField(max_length=40, verbose_name=b'Role Name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='SubPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('createdby', models.CharField(max_length=20, verbose_name=b'Created By')),
                ('updatedby', models.CharField(max_length=20, verbose_name=b'Updated By')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name=b'Sub Practice Code')),
                ('name', models.CharField(max_length=40, verbose_name=b'Sub Practice Name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Practice')),
            ],
            options={
                'verbose_name': 'Sub Practice',
                'verbose_name_plural': 'Sub Practices',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(default=None, max_length=30, verbose_name=b'Batch')),
                ('exercise', models.CharField(default=None, max_length=30, verbose_name=b'Exercise')),
                ('trainingDate', models.DateField(default=None, verbose_name=b'Start Date')),
                ('endDate', models.DateField(default=None, verbose_name=b'End Date')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.OfficeLocation', verbose_name=b'Location')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Trainer')),
            ],
        ),
        migrations.AddField(
            model_name='holiday',
            name='location',
            field=models.ManyToManyField(default=None, to='CompanyMaster.OfficeLocation'),
        ),
        migrations.AddField(
            model_name='designation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Role'),
        ),
        migrations.AddField(
            model_name='customer',
            name='CType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.CustomerType', verbose_name=b'Business Segment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Cdelivery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Account delivery manager'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Crelation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Relation', to=settings.AUTH_USER_MODEL, verbose_name=b'Account relationship manager'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.CustomerGroup', verbose_name=b'Customer Group'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pnl',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.PnL'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Currency', verbose_name=b'Currency Code'),
        ),
        migrations.AddField(
            model_name='country',
            name='region_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Region', verbose_name=b'Region code'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Country', verbose_name=b'country'),
        ),
    ]
