# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name=b'Business Unit Name')),
                ('centerType', models.CharField(choices=[(b'P', b'Profit Center'), (b'C', b'Cost Center')], default=None, max_length=2, verbose_name=b'Type of center')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('new_bu_head', models.ManyToManyField(blank=True, related_name='New_BU_Head', to=settings.AUTH_USER_MODEL, verbose_name=b'Business Unit Head')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20, verbose_name=b'comapny name')),
                ('company_legal_name', models.CharField(max_length=50, verbose_name=b'conpany legal name')),
                ('legal_HQ_address', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'legal head quarter address')),
                ('legal_HQ_city', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'legal head quarter city')),
                ('legal_HQ_state', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'legal head quarter state')),
                ('legal_HQ_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'legal head quarter zipcode')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=20, verbose_name=b'Country Code')),
                ('country_name', models.CharField(max_length=50, verbose_name=b'Country Name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('privacy_rule', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Privacy Rule')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, verbose_name=b'currency code')),
                ('currency_name', models.CharField(max_length=50, verbose_name=b'currency name')),
                ('default', models.BooleanField(default=True, verbose_name=b'Default')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Customer Name')),
                ('internal', models.BooleanField(default=False, verbose_name=b'Internal Customer')),
                ('customerCode', models.CharField(default=None, max_length=3, verbose_name=b'Customer Code')),
                ('location', models.CharField(default=None, max_length=100, verbose_name=b'Location')),
                ('seqNumber', models.PositiveIntegerField(default=1, verbose_name=b'Project ID Sequence')),
                ('cContact', models.CharField(default=None, max_length=100, verbose_name=b'Customer contact')),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('address', models.CharField(default=None, max_length=100, verbose_name=b'Address')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_group_code', models.CharField(max_length=20, verbose_name=b'customer group code')),
                ('customer_group_name', models.CharField(max_length=50, verbose_name=b'customer group name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
            ],
            options={
                'verbose_name': 'Customer Group',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'Type of Customer')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name=b'Service Line')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.BusinessUnit', verbose_name=b'BU')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Lead')),
            ],
            options={
                'verbose_name': 'Service Line',
                'verbose_name_plural': 'Service Lines',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name=b'Department Name')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name=b'Sub Department Name')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Holiday Name')),
                ('date', models.DateField(verbose_name=b'Holiday Date')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('remark', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name=b'remark')),
            ],
        ),
        migrations.CreateModel(
            name='HRActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name=b'Event Name')),
                ('date', models.DateField(verbose_name=b'Event Date')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
            options={
                'verbose_name': 'HR Activity',
                'verbose_name_plural': 'HR Activities',
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'Location Name')),
                ('city', models.CharField(max_length=15, verbose_name=b'City')),
                ('state', models.CharField(max_length=20, verbose_name=b'State')),
                ('zipcode', models.CharField(max_length=6, verbose_name=b'ZIP or PIN code ')),
                ('active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=10, verbose_name=b'region code')),
                ('region_name', models.CharField(max_length=50, verbose_name=b'region name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(default=None, max_length=30, verbose_name=b'Batch')),
                ('exercise', models.CharField(default=None, max_length=30, verbose_name=b'Exercise')),
                ('trainingDate', models.DateField(default=None, verbose_name=b'Start Date')),
                ('endDate', models.DateField(default=None, verbose_name=b'End Date')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.OfficeLocation', verbose_name=b'Location')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Trainer')),
            ],
        ),
        migrations.AddField(
            model_name='holiday',
            name='location',
            field=models.ManyToManyField(default=None, to='CompanyMaster.OfficeLocation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='CType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.CustomerType', verbose_name=b'Customer Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Cdelivery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Account delivery manager'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Crelation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Relation', to=settings.AUTH_USER_MODEL, verbose_name=b'Account relationship manager'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.CustomerGroup', verbose_name=b'Customer Group'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Currency', verbose_name=b'Currency Code'),
        ),
        migrations.AddField(
            model_name='country',
            name='region_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Region', verbose_name=b'Region code'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Country', verbose_name=b'country'),
        ),
    ]
