# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name=b'Career Band Code')),
                ('description', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Career Band Name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
            ],
            options={
                'verbose_name': 'Career Band',
                'verbose_name_plural': 'Career Bands',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('company_name', models.CharField(max_length=20, verbose_name=b'company name')),
                ('company_legal_name', models.CharField(max_length=50, verbose_name=b'company legal name')),
                ('legal_HQ_address', models.TextField(blank=True, null=True, verbose_name=b'legal head quarter address')),
                ('legal_HQ_city', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'legal head quarter city')),
                ('legal_HQ_state', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'legal head quarter state')),
                ('legal_HQ_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'legal head quarter zipcode')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('country_code', models.CharField(max_length=20, unique=True, verbose_name=b'Country Code')),
                ('country_name', models.CharField(max_length=50, verbose_name=b'Country Name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
                ('privacy_rule', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Privacy Rule')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('currency_code', models.CharField(max_length=10, unique=True, verbose_name=b'currency code')),
                ('currency_name', models.CharField(max_length=50, verbose_name=b'currency name')),
                ('default', models.BooleanField(default=True, verbose_name=b'Default')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('customer_group_code', models.CharField(max_length=20, unique=True, verbose_name=b'customer group code')),
                ('customer_group_name', models.CharField(max_length=50, verbose_name=b'customer group name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
            ],
            options={
                'verbose_name': 'Customer Group',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'Type of Customer')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name=b'Service Line')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
            options={
                'verbose_name': 'Service Line',
                'verbose_name_plural': 'Service Lines',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('createdby', models.CharField(max_length=20, verbose_name=b'Created By')),
                ('updatedby', models.CharField(max_length=20, verbose_name=b'Updated By')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name=b'Designation Name')),
                ('is_active', models.BooleanField(verbose_name=b'Is Active')),
                ('steps', models.IntegerField(verbose_name=b'Ladder Step')),
                ('career_band_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.CareerBand')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
            },
        ),
        migrations.CreateModel(
            name='HRActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name=b'Event Name')),
                ('date', models.DateField(verbose_name=b'Event Date')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
            options={
                'verbose_name': 'HR Activity',
                'verbose_name_plural': 'HR Activities',
            },
        ),
        migrations.CreateModel(
            name='KRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('createdby', models.CharField(max_length=20, verbose_name=b'Created By')),
                ('updatedby', models.CharField(max_length=20, verbose_name=b'Updated By')),
                ('series', models.IntegerField()),
                ('narration', models.TextField(verbose_name=b'KRA Narration')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Designation')),
            ],
            options={
                'verbose_name': 'KRA',
                'verbose_name_plural': 'KRAs',
            },
        ),
        migrations.CreateModel(
            name='PnL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name=b'PnL Name')),
                ('description', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'PnL Description')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PNL',
                'verbose_name_plural': 'PNLS',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('createdby', models.CharField(max_length=20, verbose_name=b'Created By')),
                ('updatedby', models.CharField(max_length=20, verbose_name=b'Updated By')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name=b'Practice Code')),
                ('name', models.CharField(max_length=20, verbose_name=b'Practice Name')),
                ('sub_practice', models.BooleanField(verbose_name=b'Has Sub Practice')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
            ],
            options={
                'verbose_name': 'Practice',
                'verbose_name_plural': 'Practices',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('createdby', models.CharField(max_length=20, verbose_name=b'Created By')),
                ('updatedby', models.CharField(max_length=20, verbose_name=b'Updated By')),
                ('region_code', models.CharField(max_length=10, unique=True, verbose_name=b'region code')),
                ('region_name', models.CharField(max_length=50, verbose_name=b'region name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active?')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name=b'Role Code')),
                ('name', models.CharField(max_length=20, verbose_name=b'Role Name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='SubPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('createdby', models.CharField(max_length=20, verbose_name=b'Created By')),
                ('updatedby', models.CharField(max_length=20, verbose_name=b'Updated By')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name=b'Sub Practice Code')),
                ('name', models.CharField(max_length=40, verbose_name=b'Sub Practice Name')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Is Active')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Practice')),
            ],
            options={
                'verbose_name': 'Sub Practice',
                'verbose_name_plural': 'Sub Practices',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(default=None, max_length=30, verbose_name=b'Batch')),
                ('exercise', models.CharField(default=None, max_length=30, verbose_name=b'Exercise')),
                ('trainingDate', models.DateField(default=None, verbose_name=b'Start Date')),
                ('endDate', models.DateField(default=None, verbose_name=b'End Date')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name=b'created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='relatedMember',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='centerType',
            field=models.CharField(choices=[(b'P', b'Profit Center'), (b'C', b'Cost Center')], default=None, max_length=2, verbose_name=b'Type of center'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='new_bu_head',
            field=models.ManyToManyField(blank=True, related_name='New_BU_Head', to=settings.AUTH_USER_MODEL, verbose_name=b'Business Unit Head'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Cdelivery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Account delivery manager'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Crelation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Relation', to=settings.AUTH_USER_MODEL, verbose_name=b'Account relationship manager'),
        ),
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True, verbose_name=b'Is Active?'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=None, max_length=100, verbose_name=b'Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cContact',
            field=models.CharField(default=None, max_length=100, verbose_name=b'Customer contact'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customerCode',
            field=models.CharField(default=None, max_length=3, verbose_name=b'Customer Code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='internal',
            field=models.BooleanField(default=False, verbose_name=b'Internal Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(default=None, max_length=100, verbose_name=b'Location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='seqNumber',
            field=models.PositiveIntegerField(default=1, verbose_name=b'Project ID Sequence'),
        ),
        migrations.AddField(
            model_name='department',
            name='billable',
            field=models.BooleanField(default=0, verbose_name=b'Is Billable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default=0, max_length=10, unique=True, verbose_name=b'Department Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='createdby',
            field=models.CharField(default=3, max_length=20, verbose_name=b'Created By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Department Head'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=b'Is Active'),
        ),
        migrations.AddField(
            model_name='department',
            name='practices',
            field=models.BooleanField(default=1, verbose_name=b'Has Practices'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updatedby',
            field=models.CharField(default=1, max_length=20, verbose_name=b'Updated By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='location',
            field=models.ManyToManyField(default=None, to='CompanyMaster.OfficeLocation'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='remark',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name=b'remark'),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='active',
            field=models.BooleanField(default=True, verbose_name=b'Is Active?'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name=b'Customer Name'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Holiday Name'),
        ),
        migrations.AddField(
            model_name='training',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.OfficeLocation', verbose_name=b'Location'),
        ),
        migrations.AddField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Trainer'),
        ),
        migrations.AddField(
            model_name='practice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Department'),
        ),
        migrations.AddField(
            model_name='practice',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Role'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='bu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.BusinessUnit', verbose_name=b'BU'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Lead'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Currency', verbose_name=b'Currency Code'),
        ),
        migrations.AddField(
            model_name='country',
            name='region_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Region', verbose_name=b'Region code'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Country', verbose_name=b'country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='CType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.CustomerType', verbose_name=b'Business Segment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.CustomerGroup', verbose_name=b'Customer Group'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pnl',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyMaster.PnL'),
        ),
    ]
