# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyMaster', '0031_auto_20160808_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssegment',
            name='pnl',
        ),
        migrations.RemoveField(
            model_name='careerladder',
            name='career_ladder_header',
        ),
        migrations.RemoveField(
            model_name='careerladder',
            name='designation',
        ),
        migrations.DeleteModel(
            name='CareerLadder',
        ),
        migrations.DeleteModel(
            name='CareerLadderHeader',
        ),
        migrations.RemoveField(
            model_name='company',
            name='HQ',
        ),
        migrations.RemoveField(
            model_name='company',
            name='locations',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='country',
            name='region_name',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.RemoveField(
            model_name='customernew',
            name='HQ_address',
        ),
        migrations.RemoveField(
            model_name='customernew',
            name='account_delivery_manager',
        ),
        migrations.RemoveField(
            model_name='customernew',
            name='account_relationship_manager',
        ),
        migrations.RemoveField(
            model_name='customernew',
            name='bill_to_address',
        ),
        migrations.RemoveField(
            model_name='customernew',
            name='business_segment',
        ),
        migrations.DeleteModel(
            name='BusinessSegment',
        ),
        migrations.RemoveField(
            model_name='customernew',
            name='ship_to_address',
        ),
        migrations.DeleteModel(
            name='CustomerNew',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='career_band_name',
        ),
        migrations.DeleteModel(
            name='CareerBand',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='role',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='designation_name',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='KRA',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PnL',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='department',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='practice_head',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='subpractice',
            name='pratice',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.RemoveField(
            model_name='subpractice',
            name='sub_practice_lead',
        ),
        migrations.DeleteModel(
            name='SubPractice',
        ),
        migrations.RemoveField(
            model_name='supporttask',
            name='department',
        ),
        migrations.DeleteModel(
            name='SupportTask',
        ),
    ]
