# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-13 07:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_number', models.IntegerField(help_text=b'8 digit number starting with 201', unique=True, validators=[django.core.validators.MinValueValidator(20100000), django.core.validators.MaxValueValidator(99999999)], verbose_name=b'SF\\Opportunity Number')),
                ('opportunity_name', models.CharField(max_length=300)),
                ('business_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Customer Contact')),
                ('account_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name=b'Project Value(in $)')),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name=b'Estimated Start Date')),
                ('end_date', models.DateField(verbose_name=b'Estimated End Date')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name=b'Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Salesforce Data',
            },
        ),
    ]
