# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 09:16
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Salesforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesforcedata',
            options={'verbose_name_plural': 'Salesforce Data'},
        ),
        migrations.AddField(
            model_name='salesforcedata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 3, 9, 15, 59, 688214, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesforcedata',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 3, 9, 16, 5, 252547, tzinfo=utc), verbose_name=b'Updated Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesforcedata',
            name='account_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesforcedata',
            name='business_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesforcedata',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Customer Contact'),
        ),
        migrations.AlterField(
            model_name='salesforcedata',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 3, 9, 16, 14, 624237, tzinfo=utc), verbose_name=b'Estimated End Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesforcedata',
            name='opportunity_number',
            field=models.IntegerField(help_text=b'8 digit number starting with 201', unique=True, validators=[django.core.validators.MinValueValidator(20100000), django.core.validators.MaxValueValidator(99999999)], verbose_name=b'SF\\Opportunity Number'),
        ),
        migrations.AlterField(
            model_name='salesforcedata',
            name='probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesforcedata',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Estimated Start Date'),
        ),
        migrations.AlterField(
            model_name='salesforcedata',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name=b'Project Value(in $)'),
        ),
    ]
